name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  issues:
    types:
      - opened

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: django
          POSTGRES_PASSWORD: django
          POSTGRES_DB: collabsphere
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Migrations
      env:
        DATABASE_URL: postgres://django:django@localhost:5432/collabsphere
        SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      run: |
        python manage.py migrate

    - name: Run Tests
      env:
        DATABASE_URL: postgres://django:django@localhost:5432/collabsphere
        SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      run: |
        python manage.py test

  handle-issue:
    if: ${{ github.event_name == 'issues' }}
    runs-on: ubuntu-latest

    steps:
    - name: Log Issue Information
      run: |
        echo "A new issue has been created."
        echo "Issue Title: ${{ github.event.issue.title }}"
        echo "Issue URL: ${{ github.event.issue.html_url }}"
        echo "Issue Body: ${{ github.event.issue.body }}"

    - name: Add Default Labels
      uses: actions-ecosystem/action-add-labels@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        labels: 'new, triage'
